### ISSUE TITLE
Add FADC integrators. 

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/EvioTool#7]
Code needs an integrator for the mode 1 data from the FADCs. 

- Use the NSB  NSA integration.
- Do a full fit with a three pole function.

**Comment by baltzell** [comment]
That option was there in EcalRawConverter, maybe someone removed it

**Comment by mholtrop** [comment]
@baltzell You are correct that this is in hps_java:org.hps.recon.ecal.EcalRawConverter2.java 
That is a whole different tree of code and is in C++. It runs a _lot_ faster.

**Comment by mholtrop** [comment]
Merged.
